### ISSUE TITLE
Google sign in method doesn't work

### ISSUE THREAD

**Issue by ghost** [Aniruddha-Tapas/UPES-SPE-Fest#6]
After you choose your account, the app hangs on the loading screen forever. I tried setting up the firebase auth and still no way to fix it.

**Comment by Aniruddha-Tapas** [comment]
Does your Google account have a display picture. If no that might be a reason that is causing a NPE. Also please post the logcat after the crash.

**Comment by ghost** [comment]
Yep I have it, still just loads up and stays on splash screen.

**Comment by ghost** [comment]
And how can I upload event's can't seem to understand that part?
