### ISSUE TITLE
Google-Service.json is missing

### ISSUE THREAD

**Issue by nerdstribe** [Aniruddha-Tapas/UPES-SPE-Fest#7]
Kindly provide this .json file. I have to go through the code to learn!

Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\ciphe\AndroidStudioProjects\UPES-SPE-Fest\app\src\debug\google-services.json
  C:\Users\ciphe\AndroidStudioProjects\UPES-SPE-Fest\app\google-services.json

Thanks :)

**Comment by Aniruddha-Tapas** [comment]
You have to use your own google-services.json file. 
https://support.google.com/firebase/answer/7015592?hl=en
______
